microcontroller:
  relayS:
    1: "Off"
    0: "On"
  lightS:
    1: "On"
    0: "Off"
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8086/eureka/}
  instance:
    instance-id: karenbot-instance
spring:
  application:
    name: karenbot